# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResonanzFit-GUI.ui'
#
# Created: Fri May 22 15:24:45 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

def ExitApp():
    sys.exit(app.exec_())


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(902, 818)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 755, 264))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame = QtGui.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_AddPath = QtGui.QPushButton(self.frame)
        self.pushButton_AddPath.setObjectName(_fromUtf8("pushButton_AddPath"))
        self.horizontalLayout.addWidget(self.pushButton_AddPath)
        self.pushButton_CheckAmpFiles = QtGui.QPushButton(self.frame)
        self.pushButton_CheckAmpFiles.setObjectName(_fromUtf8("pushButton_CheckAmpFiles"))
        self.horizontalLayout.addWidget(self.pushButton_CheckAmpFiles)
        self.pushButton_CheckPhaseFiles = QtGui.QPushButton(self.frame)
        self.pushButton_CheckPhaseFiles.setObjectName(_fromUtf8("pushButton_CheckPhaseFiles"))
        self.horizontalLayout.addWidget(self.pushButton_CheckPhaseFiles)
        self.formLayout.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout)
        self.label_Path = QtGui.QLabel(self.frame)
        self.label_Path.setObjectName(_fromUtf8("label_Path"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_Path)
        self.listView_Amps = QtGui.QListView(self.frame)
        self.listView_Amps.setEnabled(True)
        self.listView_Amps.setObjectName(_fromUtf8("listView_Amps"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.listView_Amps)
        self.listView_Phases = QtGui.QListView(self.frame)
        self.listView_Phases.setObjectName(_fromUtf8("listView_Phases"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.listView_Phases)
        self.horizontalLayout_2.addWidget(self.frame)
        spacerItem = QtGui.QSpacerItem(29, 235, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_Pixel = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_Pixel.setStyleSheet(_fromUtf8(""))
        self.spinBox_Pixel.setMaximum(9999)
        self.spinBox_Pixel.setProperty("value", 0)
        self.spinBox_Pixel.setObjectName(_fromUtf8("spinBox_Pixel"))
        self.gridLayout.addWidget(self.spinBox_Pixel, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox_Messpunkte = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_Messpunkte.setStyleSheet(_fromUtf8(""))
        self.spinBox_Messpunkte.setMaximum(9999)
        self.spinBox_Messpunkte.setProperty("value", 0)
        self.spinBox_Messpunkte.setObjectName(_fromUtf8("spinBox_Messpunkte"))
        self.gridLayout.addWidget(self.spinBox_Messpunkte, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.commandLoadAmp = QtGui.QCommandLinkButton(self.layoutWidget)
        self.commandLoadAmp.setObjectName(_fromUtf8("commandLoadAmp"))
        self.verticalLayout.addWidget(self.commandLoadAmp)
        self.commandLoadPhase = QtGui.QCommandLinkButton(self.layoutWidget)
        self.commandLoadPhase.setObjectName(_fromUtf8("commandLoadPhase"))
        self.verticalLayout.addWidget(self.commandLoadPhase)
        spacerItem1 = QtGui.QSpacerItem(158, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBox_FreqMin = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_FreqMin.setMaximum(999000)
        self.spinBox_FreqMin.setSingleStep(500)
        self.spinBox_FreqMin.setObjectName(_fromUtf8("spinBox_FreqMin"))
        self.gridLayout_2.addWidget(self.spinBox_FreqMin, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.spinBox_FreqMax = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_FreqMax.setMaximum(999000)
        self.spinBox_FreqMax.setSingleStep(500)
        self.spinBox_FreqMax.setObjectName(_fromUtf8("spinBox_FreqMax"))
        self.gridLayout_2.addWidget(self.spinBox_FreqMax, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.groupBox_SingleResonance = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_SingleResonance.setGeometry(QtCore.QRect(10, 290, 401, 301))
        self.groupBox_SingleResonance.setObjectName(_fromUtf8("groupBox_SingleResonance"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_SingleResonance)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 40, 103, 60))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_XPoint = QtGui.QLabel(self.layoutWidget1)
        self.label_XPoint.setObjectName(_fromUtf8("label_XPoint"))
        self.gridLayout_3.addWidget(self.label_XPoint, 0, 0, 1, 1)
        self.spinBox_XSingle = QtGui.QSpinBox(self.layoutWidget1)
        self.spinBox_XSingle.setMaximum(999)
        self.spinBox_XSingle.setObjectName(_fromUtf8("spinBox_XSingle"))
        self.gridLayout_3.addWidget(self.spinBox_XSingle, 0, 1, 1, 1)
        self.label_YPoint = QtGui.QLabel(self.layoutWidget1)
        self.label_YPoint.setObjectName(_fromUtf8("label_YPoint"))
        self.gridLayout_3.addWidget(self.label_YPoint, 1, 0, 1, 1)
        self.spinBox_YSingle = QtGui.QSpinBox(self.layoutWidget1)
        self.spinBox_YSingle.setMaximum(999)
        self.spinBox_YSingle.setObjectName(_fromUtf8("spinBox_YSingle"))
        self.gridLayout_3.addWidget(self.spinBox_YSingle, 1, 1, 1, 1)
        self.groupBox_SingleResonance_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_SingleResonance_2.setGeometry(QtCore.QRect(440, 290, 401, 301))
        self.groupBox_SingleResonance_2.setObjectName(_fromUtf8("groupBox_SingleResonance_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClose)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_AddPath.setText(_translate("MainWindow", "Add Path", None))
        self.pushButton_CheckAmpFiles.setText(_translate("MainWindow", "Check for Amp Files", None))
        self.pushButton_CheckPhaseFiles.setText(_translate("MainWindow", "Check for Phase Files", None))
        self.label_Path.setText(_translate("MainWindow", "Path", None))
        self.label.setText(_translate("MainWindow", "Pixel", None))
        self.spinBox_Pixel.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Number of Pixels</p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "Messpunkte pro Pixel", None))
        self.spinBox_Messpunkte.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Number of Pixels</p></body></html>", None))
        self.commandLoadAmp.setText(_translate("MainWindow", "Load Amp-Data", None))
        self.commandLoadPhase.setText(_translate("MainWindow", "Load Phase-Data", None))
        self.label_3.setText(_translate("MainWindow", "Freq Min (Hz)", None))
        self.label_4.setText(_translate("MainWindow", "Freq Max (Hz)", None))
        self.groupBox_SingleResonance.setTitle(_translate("MainWindow", "Single Resonance ", None))
        self.label_XPoint.setText(_translate("MainWindow", "X-Point", None))
        self.label_YPoint.setText(_translate("MainWindow", "Y-Point", None))
        self.groupBox_SingleResonance_2.setTitle(_translate("MainWindow", "Initial Guess Fitparameter", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpen.setText(_translate("MainWindow", "&Open", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionClose.setText(_translate("MainWindow", "&Quit", None))
        self.actionClose.setToolTip(_translate("MainWindow", "Quit Application", None))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+Q", None))



if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

