# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dokumente/BE-ESM-Analysis/Design/RasterLaden.ui'
#
# Created: Wed Dec  9 13:17:53 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RasterLaden(object):
    def setupUi(self, RasterLaden):
        RasterLaden.setObjectName(_fromUtf8("RasterLaden"))
        RasterLaden.resize(404, 570)
        self.centralwidget = QtGui.QWidget(RasterLaden)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget_param = QtGui.QWidget(self.centralwidget)
        self.widget_param.setGeometry(QtCore.QRect(10, 150, 381, 371))
        self.widget_param.setObjectName(_fromUtf8("widget_param"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.widget_param)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 379, 371))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticallayout2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticallayout2.setMargin(0)
        self.verticallayout2.setObjectName(_fromUtf8("verticallayout2"))
        self.label_bereich = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_bereich.setObjectName(_fromUtf8("label_bereich"))
        self.verticallayout2.addWidget(self.label_bereich)
        self.horizontallayout3 = QtGui.QHBoxLayout()
        self.horizontallayout3.setObjectName(_fromUtf8("horizontallayout3"))
        self.label_bereich_links = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_bereich_links.sizePolicy().hasHeightForWidth())
        self.label_bereich_links.setSizePolicy(sizePolicy)
        self.label_bereich_links.setObjectName(_fromUtf8("label_bereich_links"))
        self.horizontallayout3.addWidget(self.label_bereich_links)
        self.box_bereich_links = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.box_bereich_links.setMaximum(999999999)
        self.box_bereich_links.setObjectName(_fromUtf8("box_bereich_links"))
        self.horizontallayout3.addWidget(self.box_bereich_links)
        self.label_bereich_rechts = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_bereich_rechts.sizePolicy().hasHeightForWidth())
        self.label_bereich_rechts.setSizePolicy(sizePolicy)
        self.label_bereich_rechts.setObjectName(_fromUtf8("label_bereich_rechts"))
        self.horizontallayout3.addWidget(self.label_bereich_rechts)
        self.box_bereich_rechts = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.box_bereich_rechts.setMinimum(-999999999)
        self.box_bereich_rechts.setMaximum(0)
        self.box_bereich_rechts.setObjectName(_fromUtf8("box_bereich_rechts"))
        self.horizontallayout3.addWidget(self.box_bereich_rechts)
        self.verticallayout2.addLayout(self.horizontallayout3)
        self.line = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticallayout2.addWidget(self.line)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticallayout2.addItem(spacerItem)
        self.horizontallayout4 = QtGui.QHBoxLayout()
        self.horizontallayout4.setObjectName(_fromUtf8("horizontallayout4"))
        self.label_methode = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_methode.sizePolicy().hasHeightForWidth())
        self.label_methode.setSizePolicy(sizePolicy)
        self.label_methode.setObjectName(_fromUtf8("label_methode"))
        self.horizontallayout4.addWidget(self.label_methode)
        self.box_methode = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.box_methode.setObjectName(_fromUtf8("box_methode"))
        self.box_methode.addItem(_fromUtf8(""))
        self.box_methode.addItem(_fromUtf8(""))
        self.horizontallayout4.addWidget(self.box_methode)
        self.verticallayout2.addLayout(self.horizontallayout4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_phase_fit = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_phase_fit.setObjectName(_fromUtf8("label_phase_fit"))
        self.horizontalLayout.addWidget(self.label_phase_fit)
        self.box_phase_fit = QtGui.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_phase_fit.sizePolicy().hasHeightForWidth())
        self.box_phase_fit.setSizePolicy(sizePolicy)
        self.box_phase_fit.setObjectName(_fromUtf8("box_phase_fit"))
        self.box_phase_fit.addItem(_fromUtf8(""))
        self.box_phase_fit.addItem(_fromUtf8(""))
        self.box_phase_fit.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.box_phase_fit)
        self.label_phase_versatz = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_phase_versatz.setObjectName(_fromUtf8("label_phase_versatz"))
        self.horizontalLayout.addWidget(self.label_phase_versatz)
        self.box_phase_versatz = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.box_phase_versatz.setMinimum(-999999)
        self.box_phase_versatz.setMaximum(999999)
        self.box_phase_versatz.setProperty("value", 30)
        self.box_phase_versatz.setObjectName(_fromUtf8("box_phase_versatz"))
        self.horizontalLayout.addWidget(self.box_phase_versatz)
        self.verticallayout2.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticallayout2.addItem(spacerItem1)
        self.label_savgol = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_savgol.setObjectName(_fromUtf8("label_savgol"))
        self.verticallayout2.addWidget(self.label_savgol)
        self.horizontallayout5 = QtGui.QHBoxLayout()
        self.horizontallayout5.setObjectName(_fromUtf8("horizontallayout5"))
        self.label_fenster = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_fenster.setObjectName(_fromUtf8("label_fenster"))
        self.horizontallayout5.addWidget(self.label_fenster)
        self.box_fenster = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.box_fenster.setMinimum(1)
        self.box_fenster.setProperty("value", 15)
        self.box_fenster.setObjectName(_fromUtf8("box_fenster"))
        self.horizontallayout5.addWidget(self.box_fenster)
        self.label_ordnung = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_ordnung.setObjectName(_fromUtf8("label_ordnung"))
        self.horizontallayout5.addWidget(self.label_ordnung)
        self.box_ordnung = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.box_ordnung.setMinimum(1)
        self.box_ordnung.setProperty("value", 3)
        self.box_ordnung.setObjectName(_fromUtf8("box_ordnung"))
        self.horizontallayout5.addWidget(self.box_ordnung)
        self.verticallayout2.addLayout(self.horizontallayout5)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticallayout2.addItem(spacerItem2)
        self.gridlayout2 = QtGui.QGridLayout()
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.box_guete_min = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.box_guete_min.setDecimals(3)
        self.box_guete_min.setMinimum(-999999.999)
        self.box_guete_min.setMaximum(999999.999)
        self.box_guete_min.setProperty("value", 5.0)
        self.box_guete_min.setObjectName(_fromUtf8("box_guete_min"))
        self.gridlayout2.addWidget(self.box_guete_min, 3, 1, 1, 1)
        self.label_guete = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_guete.sizePolicy().hasHeightForWidth())
        self.label_guete.setSizePolicy(sizePolicy)
        self.label_guete.setObjectName(_fromUtf8("label_guete"))
        self.gridlayout2.addWidget(self.label_guete, 3, 0, 1, 1)
        self.box_untergrund_max = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.box_untergrund_max.setDecimals(3)
        self.box_untergrund_max.setMaximum(999999.999)
        self.box_untergrund_max.setProperty("value", 5.0)
        self.box_untergrund_max.setObjectName(_fromUtf8("box_untergrund_max"))
        self.gridlayout2.addWidget(self.box_untergrund_max, 2, 2, 1, 1)
        self.box_amp_min = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.box_amp_min.setDecimals(3)
        self.box_amp_min.setMaximum(999999.999)
        self.box_amp_min.setProperty("value", 10.0)
        self.box_amp_min.setObjectName(_fromUtf8("box_amp_min"))
        self.gridlayout2.addWidget(self.box_amp_min, 1, 1, 1, 1)
        self.box_untergrund_min = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.box_untergrund_min.setDecimals(3)
        self.box_untergrund_min.setMaximum(999999.999)
        self.box_untergrund_min.setObjectName(_fromUtf8("box_untergrund_min"))
        self.gridlayout2.addWidget(self.box_untergrund_min, 2, 1, 1, 1)
        self.box_amp_max = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.box_amp_max.setDecimals(3)
        self.box_amp_max.setMinimum(0.0)
        self.box_amp_max.setMaximum(999999.999)
        self.box_amp_max.setProperty("value", 100.0)
        self.box_amp_max.setObjectName(_fromUtf8("box_amp_max"))
        self.gridlayout2.addWidget(self.box_amp_max, 1, 2, 1, 1)
        self.label_untergrund = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_untergrund.sizePolicy().hasHeightForWidth())
        self.label_untergrund.setSizePolicy(sizePolicy)
        self.label_untergrund.setObjectName(_fromUtf8("label_untergrund"))
        self.gridlayout2.addWidget(self.label_untergrund, 2, 0, 1, 1)
        self.label_amp = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_amp.sizePolicy().hasHeightForWidth())
        self.label_amp.setSizePolicy(sizePolicy)
        self.label_amp.setObjectName(_fromUtf8("label_amp"))
        self.gridlayout2.addWidget(self.label_amp, 1, 0, 1, 1)
        self.box_guete_max = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.box_guete_max.setDecimals(3)
        self.box_guete_max.setMinimum(-999999.999)
        self.box_guete_max.setMaximum(999999.999)
        self.box_guete_max.setProperty("value", 25.0)
        self.box_guete_max.setObjectName(_fromUtf8("box_guete_max"))
        self.gridlayout2.addWidget(self.box_guete_max, 3, 2, 1, 1)
        self.label_fitparameter = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_fitparameter.setObjectName(_fromUtf8("label_fitparameter"))
        self.gridlayout2.addWidget(self.label_fitparameter, 0, 0, 1, 1)
        self.label_min = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_min.setAlignment(QtCore.Qt.AlignCenter)
        self.label_min.setObjectName(_fromUtf8("label_min"))
        self.gridlayout2.addWidget(self.label_min, 0, 1, 1, 1)
        self.label_max = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_max.setAlignment(QtCore.Qt.AlignCenter)
        self.label_max.setObjectName(_fromUtf8("label_max"))
        self.gridlayout2.addWidget(self.label_max, 0, 2, 1, 1)
        self.verticallayout2.addLayout(self.gridlayout2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticallayout2.addItem(spacerItem3)
        self.button_vorschau = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.button_vorschau.setEnabled(False)
        self.button_vorschau.setCheckable(True)
        self.button_vorschau.setObjectName(_fromUtf8("button_vorschau"))
        self.verticallayout2.addWidget(self.button_vorschau)
        self.widget_fit = QtGui.QWidget(self.centralwidget)
        self.widget_fit.setGeometry(QtCore.QRect(10, 530, 381, 31))
        self.widget_fit.setObjectName(_fromUtf8("widget_fit"))
        self.layoutWidget = QtGui.QWidget(self.widget_fit)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 381, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontallayout0 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontallayout0.setMargin(0)
        self.horizontallayout0.setObjectName(_fromUtf8("horizontallayout0"))
        self.button_fitten = QtGui.QPushButton(self.layoutWidget)
        self.button_fitten.setEnabled(True)
        self.button_fitten.setCheckable(True)
        self.button_fitten.setObjectName(_fromUtf8("button_fitten"))
        self.horizontallayout0.addWidget(self.button_fitten)
        self.progress_bar = QtGui.QProgressBar(self.layoutWidget)
        self.progress_bar.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar.sizePolicy().hasHeightForWidth())
        self.progress_bar.setSizePolicy(sizePolicy)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName(_fromUtf8("progress_bar"))
        self.horizontallayout0.addWidget(self.progress_bar)
        self.widget_pfad = QtGui.QWidget(self.centralwidget)
        self.widget_pfad.setGeometry(QtCore.QRect(10, 10, 381, 131))
        self.widget_pfad.setObjectName(_fromUtf8("widget_pfad"))
        self.verticalLayoutWidget = QtGui.QWidget(self.widget_pfad)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 381, 131))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticallayout3 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticallayout3.setMargin(0)
        self.verticallayout3.setObjectName(_fromUtf8("verticallayout3"))
        self.horizontallayout2 = QtGui.QHBoxLayout()
        self.horizontallayout2.setObjectName(_fromUtf8("horizontallayout2"))
        self.edit_pfad = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.edit_pfad.setText(_fromUtf8(""))
        self.edit_pfad.setObjectName(_fromUtf8("edit_pfad"))
        self.horizontallayout2.addWidget(self.edit_pfad)
        self.button_aendern = QtGui.QPushButton(self.verticalLayoutWidget)
        self.button_aendern.setEnabled(True)
        self.button_aendern.setObjectName(_fromUtf8("button_aendern"))
        self.horizontallayout2.addWidget(self.button_aendern)
        self.verticallayout3.addLayout(self.horizontallayout2)
        self.horizontallayout1 = QtGui.QHBoxLayout()
        self.horizontallayout1.setObjectName(_fromUtf8("horizontallayout1"))
        self.gridlayout0 = QtGui.QGridLayout()
        self.gridlayout0.setObjectName(_fromUtf8("gridlayout0"))
        self.box_df = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.box_df.setStyleSheet(_fromUtf8(""))
        self.box_df.setMinimum(1)
        self.box_df.setMaximum(9999)
        self.box_df.setProperty("value", 1)
        self.box_df.setObjectName(_fromUtf8("box_df"))
        self.gridlayout0.addWidget(self.box_df, 1, 1, 1, 1)
        self.label_df = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_df.setObjectName(_fromUtf8("label_df"))
        self.gridlayout0.addWidget(self.label_df, 1, 0, 1, 1)
        self.box_pixel = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.box_pixel.setStyleSheet(_fromUtf8(""))
        self.box_pixel.setMinimum(1)
        self.box_pixel.setMaximum(9999)
        self.box_pixel.setProperty("value", 1)
        self.box_pixel.setObjectName(_fromUtf8("box_pixel"))
        self.gridlayout0.addWidget(self.box_pixel, 2, 1, 1, 1)
        self.label_pixel = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_pixel.setObjectName(_fromUtf8("label_pixel"))
        self.gridlayout0.addWidget(self.label_pixel, 2, 0, 1, 1)
        self.horizontallayout1.addLayout(self.gridlayout0)
        spacerItem4 = QtGui.QSpacerItem(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontallayout1.addItem(spacerItem4)
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.label_fmin = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_fmin.setObjectName(_fromUtf8("label_fmin"))
        self.gridlayout1.addWidget(self.label_fmin, 0, 0, 1, 1)
        self.label_fmax = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_fmax.setObjectName(_fromUtf8("label_fmax"))
        self.gridlayout1.addWidget(self.label_fmax, 1, 0, 1, 1)
        self.box_fmin = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.box_fmin.setDecimals(3)
        self.box_fmin.setMaximum(999.0)
        self.box_fmin.setSingleStep(0.5)
        self.box_fmin.setObjectName(_fromUtf8("box_fmin"))
        self.gridlayout1.addWidget(self.box_fmin, 0, 1, 1, 1)
        self.box_fmax = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.box_fmax.setDecimals(3)
        self.box_fmax.setMinimum(0.5)
        self.box_fmax.setMaximum(999.0)
        self.box_fmax.setSingleStep(0.5)
        self.box_fmax.setObjectName(_fromUtf8("box_fmax"))
        self.gridlayout1.addWidget(self.box_fmax, 1, 1, 1, 1)
        self.horizontallayout1.addLayout(self.gridlayout1)
        self.verticallayout3.addLayout(self.horizontallayout1)
        self.button_konfig = QtGui.QPushButton(self.verticalLayoutWidget)
        self.button_konfig.setObjectName(_fromUtf8("button_konfig"))
        self.verticallayout3.addWidget(self.button_konfig)
        RasterLaden.setCentralWidget(self.centralwidget)

        self.retranslateUi(RasterLaden)
        QtCore.QMetaObject.connectSlotsByName(RasterLaden)

    def retranslateUi(self, RasterLaden):
        RasterLaden.setWindowTitle(_translate("RasterLaden", "Resonanz Fit - Messung einlesen", None))
        self.label_bereich.setText(_translate("RasterLaden", "Frequenzbereich begrenzen (in Messpunkten):", None))
        self.label_bereich_links.setText(_translate("RasterLaden", "links:", None))
        self.label_bereich_rechts.setText(_translate("RasterLaden", "rechts:", None))
        self.label_methode.setText(_translate("RasterLaden", "Lorentzverteilung", None))
        self.box_methode.setItemText(0, _translate("RasterLaden", "Antreibendes System", None))
        self.box_methode.setItemText(1, _translate("RasterLaden", "Cantilever", None))
        self.label_phase_fit.setText(_translate("RasterLaden", "Phase", None))
        self.box_phase_fit.setItemText(0, _translate("RasterLaden", "Lorentz-Fit (physikalisch)", None))
        self.box_phase_fit.setItemText(1, _translate("RasterLaden", "Phänomenologisch (zuverlässig)", None))
        self.box_phase_fit.setItemText(2, _translate("RasterLaden", "Aus den Messwerten (ohne Fit)", None))
        self.label_phase_versatz.setText(_translate("RasterLaden", "Versatz", None))
        self.label_savgol.setText(_translate("RasterLaden", "Savitzky-Golay-Filter:", None))
        self.label_fenster.setText(_translate("RasterLaden", "Koeffizientenanzahl", None))
        self.label_ordnung.setText(_translate("RasterLaden", "Ordnung des Polynoms", None))
        self.label_guete.setText(_translate("RasterLaden", "Güte:", None))
        self.label_untergrund.setText(_translate("RasterLaden", "Untergrund:", None))
        self.label_amp.setText(_translate("RasterLaden", "Amplitude:", None))
        self.label_fitparameter.setText(_translate("RasterLaden", "Fitparameter", None))
        self.label_min.setText(_translate("RasterLaden", "min", None))
        self.label_max.setText(_translate("RasterLaden", "max", None))
        self.button_vorschau.setText(_translate("RasterLaden", "Fitvorschau anzeigen", None))
        self.button_fitten.setText(_translate("RasterLaden", "Fitten", None))
        self.button_aendern.setText(_translate("RasterLaden", "Ändern...", None))
        self.label_df.setText(_translate("RasterLaden", "delta f (Hz)", None))
        self.label_pixel.setText(_translate("RasterLaden", "Pixel (quadratisch)", None))
        self.label_fmin.setText(_translate("RasterLaden", "Freq Min (kHz)", None))
        self.label_fmax.setText(_translate("RasterLaden", "Freq Max (kHz)", None))
        self.button_konfig.setText(_translate("RasterLaden", "Messkonfiguration aus Datei einlesen", None))

